### ISSUE TITLE
Implement TaskOptions for capabliity interpretation

### ISSUE THREAD

**Issue by jviolette123** [irs1318dev/irsScouting2017#20]
In the game table, there is an enums column of the form option1|option2|option3

Create a table called TaskOptions
id, task, type, optionName
14, 'startingLocation', 'capability', 'boiler'
15, 'startingLocation', 'capability', 'center'
16, 'startingLocation', 'capability', 'retrieval'

The combination of each  task, type, optionName is unique.
For a given task with an enum measure type, add one entry for each option in the enums column, with type 'capability'  

At runtime, load the TaskOptions table into 
taskoption_ids dict.
key: optionId
value: task taskName-optionName

taskoptions dict.
key: taskName-optionName
value: task optionId

When we run the transformMeasure function for an enum measure type, we are going to accept a string capability (the value of capability is the optionName).  We will combine the taskName and optionName in the format 'taskName-optionName" . We are going to look up the option id from taskoptions, and return that value as the capability.

Key is built using these expressions:
PostGres: task_name||'-'||option_name
Python: '{}-{}'.format(taskName, optionName)

Within matchteamtasks, when we read an enum measure type from the measures table, the capability value is a task optionId.  When constructing the json return value for the "capability", we will look up that name from the  taskoption_ids and return the optionName in the "capablity" field, having stripped the taskName from the value.

Extract the optionName from the dictionary and parse the taskOption in python:
from parse import *
taskOption = taskoption_ids[capability]
result = parse("{task}-{option}", taskOption)
optionName = result['option']

**Comment by jviolette123** [comment]
Pending insert game task_options row insertion.
Pending matchteamtasks integration

**Comment by samika2000** [comment]
"ON CONFLICT "
 "DO UPDATE "
"SET actor=:actor, task=:task, claim=:claim, auto=:auto, teleop=:teleop, finish=:finish;")
